# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\服务器文件\Python projects\GUI\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QLabel, QLineEdit, QTableWidget
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton
from PyQt5 import QtCore, QtGui, QtWidgets
import obspy
from obspy.signal.trigger import classic_sta_lta, trigger_onset
import numpy as np
import torch
import os
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
import utils
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(200, 420, 271, 31))
        self.comboBox.setStyleSheet("font: 12pt \"Arial\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.show_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.show_1.setGeometry(QtCore.QRect(499, 375, 471, 141))
        self.show_1.setStyleSheet("border: 1px solid black;")
        self.show_1.setObjectName("show_1")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(20, 0, 221, 61))
        self.label_1.setObjectName("label_1")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 60, 260, 31))
        self.pushButton_1.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(290, 60, 175, 31))
        self.lineEdit_1.setStyleSheet("border: 1px solid black;\n"
                "font: 12pt \"Arial\";")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 360, 321, 31))
        self.pushButton_5.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 410, 181, 61))
        self.label_8.setObjectName("label_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 520, 451, 31))
        self.pushButton_7.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 210, 221, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 260, 101, 41))
        self.label_3.setStyleSheet("font: 12pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 260, 101, 41))
        self.label_4.setStyleSheet("font: 12pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 270, 61, 20))
        self.lineEdit_4.setStyleSheet("border: 1px solid black;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(380, 270, 61, 20))
        self.lineEdit_5.setStyleSheet("border: 1px solid black;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 310, 131, 41))
        self.label_5.setStyleSheet("font: 12pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 320, 61, 20))
        self.lineEdit_6.setStyleSheet("border: 1px solid black;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(380, 320, 61, 20))
        self.lineEdit_7.setStyleSheet("border: 1px solid black;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(469, 10, 31, 551))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 200, 471, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 390, 471, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 10, 21, 551))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 1, 471, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 550, 471, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(500, 10, 51, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(499, 345, 71, 31))
        self.label_10.setObjectName("label_10")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 310, 121, 41))
        self.label_6.setStyleSheet("font: 12pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(810, 520, 161, 31))
        self.pushButton_8.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.widget_1 = QtWidgets.QWidget(self.centralwidget)
        self.widget_1.setGeometry(QtCore.QRect(499, 39, 471, 81))
        self.widget_1.setStyleSheet("border: 1px solid black;\n"
                "background-color: rgb(255, 255, 255);")
        self.widget_1.setObjectName("widget_1")
        self.widget_1.setLayout(QVBoxLayout())
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(480, 330, 501, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(480, 1, 501, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(480, 550, 501, 21))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(965, 10, 31, 551))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(500, 140, 471, 81))
        self.widget_2.setStyleSheet("border: 1px solid black;\n"
                "background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.widget_2.setLayout(QVBoxLayout())
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(500, 240, 471, 81))
        self.widget_3.setStyleSheet("border: 1px solid black;\n"
                "background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.widget_3.setLayout(QVBoxLayout())
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 110, 260, 31))
        self.pushButton_2.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 110, 175, 31))
        self.lineEdit_2.setStyleSheet("border: 1px solid black;\n"
                "font: 12pt \"Arial\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 160, 260, 31))
        self.pushButton_3.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(290, 160, 175, 31))
        self.lineEdit_3.setStyleSheet("border: 1px solid black;\n"
                "font: 12pt \"Arial\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 120, 16, 16))
        self.label.setStyleSheet("font: 9pt \"Arial\";")
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(740, 220, 16, 16))
        self.label_11.setStyleSheet("font: 9pt \"Arial\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(740, 320, 16, 16))
        self.label_12.setStyleSheet("font: 9pt \"Arial\";")
        self.label_12.setObjectName("label_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 360, 101, 31))
        self.pushButton_4.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 470, 190, 31))
        self.pushButton_6.setStyleSheet("font: 12pt \"Arial\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(220, 470, 245, 31))
        self.lineEdit_8.setStyleSheet("border: 1px solid black;\n"
                "font: 12pt \"Arial\";")
        self.lineEdit_8.setObjectName("lineEdit_8")

        # 为按钮绑定功能函数
        self.pushButton_1.clicked.connect(self.uploadfileZ)  # 选择地震SAC文件Z 并plot
        self.pushButton_2.clicked.connect(self.uploadfileE)  # 选择地震SAC文件E 并plot
        self.pushButton_3.clicked.connect(self.uploadfileN)  # 选择地震SAC文件N 并plot
        self.pushButton_4.clicked.connect(self.default)  #设置 STALTA 参数默认值
        self.pushButton_5.clicked.connect(self.stalta)   #stalta筛选疑似地震片段
        self.pushButton_6.clicked.connect(self.choosefile) #选择保存路径
        self.pushButton_8.clicked.connect(self.clear)       # 清空选择

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Seismic Signal Classification System"))
        self.comboBox.setItemText(0, _translate("MainWindow", "AlexNet"))
        self.comboBox.setItemText(1, _translate("MainWindow", "VGG11"))
        self.comboBox.setItemText(2, _translate("MainWindow", "GoogleNet"))
        self.comboBox.setItemText(3, _translate("MainWindow", "ResNet18"))
        self.comboBox.setItemText(4, _translate("MainWindow", "VIT"))
        self.comboBox.setItemText(5, _translate("MainWindow", "CCT"))
        self.comboBox.setItemText(6, _translate("MainWindow", "CapsNet"))
        self.comboBox.setItemText(7, _translate("MainWindow", "CapsNet+Res"))
        self.comboBox.setItemText(8, _translate("MainWindow", "CapsNet+Res+SE"))
        self.comboBox.setItemText(9, _translate("MainWindow", "CapsNet+CCT"))
        self.show_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Import Continuous Waveforms：</span></p></body></html>"))
        self.pushButton_1.setText(_translate("MainWindow", "Import Vertical Component (Z)"))
        self.lineEdit_1.setPlaceholderText(_translate("MainWindow", "SAC File Path"))
        self.pushButton_5.setText(_translate("MainWindow", "Detect Segments (STA/LTA)"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Pretrained Model：</span></p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Run Classification"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">STA/LTA Event Detection：</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">THRESH_ON</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">THRESH_OFF</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">SHORT_WINDOW</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#000000;\">PLOT</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#000000;\">RESULT</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">LONG_WINDOW</span></p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "Clear Log"))
        self.pushButton_2.setText(_translate("MainWindow", "Import East–West Component (E)"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "SAC File Path"))
        self.pushButton_3.setText(_translate("MainWindow", "Import North–South Component (N)"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "SAC File Path"))
        self.label.setText(_translate("MainWindow", "Z"))
        self.label_11.setText(_translate("MainWindow", "E"))
        self.label_12.setText(_translate("MainWindow", "N"))
        self.pushButton_4.setText(_translate("MainWindow", "Defaults"))
        self.pushButton_6.setText(_translate("MainWindow", "Select Output Folder"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Output Folder"))

        # 添加功能方法的定义
        #加载连续波形文件
    
    def uploadfileZ(self):
        file_pathZ, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Select SAC File", "", "SAC Files (*.sac)")
        if file_pathZ:
            #显示路径
            self.lineEdit_1.setText(file_pathZ)
            # 读取 SAC 文件
            input = obspy.read(file_pathZ)[0]

            # 获取文件统计信息
            sampling_interval = input.stats.sac.delta
            sampling_frequency = int(1 / sampling_interval)
            total_point = input.stats.npts  # 总数据点数
            total_time = total_point * sampling_interval  # 总时间长度
            total_t = np.arange(0, total_time, sampling_interval)

            # 绘制波形图
            plt.figure(figsize=(18, 10))
            plt.plot(total_t[:len(input.data)], input.data, 'k', linewidth=1)
            plt.xlabel("Time (s)")
            plt.grid(True, linestyle='--', alpha=0.7)
            # 移除横纵坐标刻度数字
            plt.gca().set_xticks([])  # 移除横坐标刻度数字
            plt.gca().set_yticks([])  # 移除纵坐标刻度数字
            plt.tight_layout()

            # 嵌入到 GUI 中
            canvas = FigureCanvas(plt.gcf())
            layout = self.widget_1.layout()   # 获取当前显示图像的布局
            # for i in reversed(range(layout.count())):  # 清除旧图
            #     layout.itemAt(i).widget().setParent(None)
            # layout.addWidget(canvas)
            
            # 清空布局中的旧组件
            while layout.count():
                item = layout.takeAt(0)
                if item.widget():
                    item.widget().deleteLater()  # 安全销毁组件
            # 添加新的组件（图像画布）
            layout.addWidget(canvas)           
    
    def uploadfileE(self):
        file_pathE, _ = QtWidgets.QFileDialog.getOpenFileName(None, "选择 SAC 文件", "", "SAC Files (*.sac)")
        if file_pathE:
            #显示路径
            self.lineEdit_2.setText(file_pathE)

            # 读取 SAC 文件
            input = obspy.read(file_pathE)[0]

            # 获取文件统计信息
            sampling_interval = input.stats.sac.delta
            sampling_frequency = int(1 / sampling_interval)
            total_point = input.stats.npts  # 总数据点数
            total_time = total_point * sampling_interval  # 总时间长度
            total_t = np.arange(0, total_time, sampling_interval)

            # 绘制波形图
            plt.figure(figsize=(18, 10))
            plt.plot(total_t[:len(input.data)], input.data, 'k', linewidth=1)
            plt.xlabel("Time (s)")
            plt.grid(True, linestyle='--', alpha=0.7)
            plt.gca().set_xticks([])  # 移除横坐标刻度数字
            plt.gca().set_yticks([])  # 移除纵坐标刻度数字
            plt.tight_layout()
            # 嵌入到 GUI 中
            canvas = FigureCanvas(plt.gcf())
            layout = self.widget_2.layout()   # 获取当前显示图像的布局
           
            # for i in reversed(range(layout.count())):  # 清除旧图
            #     layout.itemAt(i).widget().setParent(None)
            # layout.addWidget(canvas)
            
            # 清空布局中的旧组件
            while layout.count():
                item = layout.takeAt(0)
                if item.widget():
                    item.widget().deleteLater()  # 安全销毁组件
            # 添加新的组件（图像画布）
            layout.addWidget(canvas)
    
    def uploadfileN(self):
        file_pathN, _ = QtWidgets.QFileDialog.getOpenFileName(None, "选择 SAC 文件", "", "SAC Files (*.sac)")
        if file_pathN:
            #显示路径
            self.lineEdit_3.setText(file_pathN)

            # 读取 SAC 文件
            input = obspy.read(file_pathN)[0]

            # 获取文件统计信息
            sampling_interval = input.stats.sac.delta
            sampling_frequency = int(1 / sampling_interval)
            total_point = input.stats.npts  # 总数据点数
            total_time = total_point * sampling_interval  # 总时间长度
            total_t = np.arange(0, total_time, sampling_interval)

            # 绘制波形图
            plt.figure(figsize=(18, 10))
            plt.plot(total_t[:len(input.data)], input.data, 'k', linewidth=1)
            plt.xlabel("Time (s)")
            plt.grid(True, linestyle='--', alpha=0.7)
            plt.gca().set_xticks([])  # 移除横坐标刻度数字
            plt.gca().set_yticks([])  # 移除纵坐标刻度数字
            plt.tight_layout()

            # 嵌入到 GUI 中
            canvas = FigureCanvas(plt.gcf())
            layout = self.widget_3.layout()   # 获取当前显示图像的布局
           
            # for i in reversed(range(layout.count())):  # 清除旧图
            #     layout.itemAt(i).widget().setParent(None)
            # layout.addWidget(canvas)
            
            # 清空布局中的旧组件
            while layout.count():
                item = layout.takeAt(0)
                if item.widget():
                    item.widget().deleteLater()  # 安全销毁组件
            # 添加新的组件（图像画布）
            layout.addWidget(canvas)

    #设置 STALTA 参数默认值
    def default(self):
        THRESH_ON = 2
        THRESH_OFF = 0.5
        SHORT_WINDOW = 1
        LONG_WINDOW = 10
      
        # 设置默认值到 QLineEdit
        self.lineEdit_4.setText(str(THRESH_ON))     
        self.lineEdit_5.setText(str(THRESH_OFF))    
        self.lineEdit_6.setText(str(SHORT_WINDOW))   
        self.lineEdit_7.setText(str(LONG_WINDOW))   

    #STA/LTA
    def stalta(self):
        file_pathZ = self.lineEdit_1.text()
        file_pathE = self.lineEdit_2.text()
        file_pathN = self.lineEdit_3.text()
        if not file_pathZ:
            self.show_1.setText("Please provide the Z file path.")
            return
        if not file_pathE:
            self.show_1.setText("Please provide the E file path.")
            return
        if not file_pathN:
            self.show_1.setText("Please provide the N file path.")
            return
        try:
            # 读取文件
            input_trace = obspy.read(file_pathZ)[0]
            input_E = obspy.read(file_pathE)[0]
            input_N = obspy.read(file_pathN)[0]
            # 读取参数，设置默认值
            windows = 60  # 每个事件的总窗口长度（秒）
            try:
                THRESH_ON = float(self.lineEdit_4.text())
                THRESH_OFF = float(self.lineEdit_5.text())
                SHORT_WINDOW = float(self.lineEdit_6.text())
                LONG_WINDOW = float(self.lineEdit_7.text())
            except ValueError:
                self.show_1.setText("Invalid STA/LTA parameters. Please check your inputs.")
                return
            # 采样信息
            sampling_interval = input_trace.stats.sac.delta
            sampling_frequency = int(1 / sampling_interval)
            # 数据预处理
            input_tensor = torch.tensor(input_trace.data, dtype=torch.float32)
            detrended_data = utils.detrend(input_tensor)  # 去趋势
            filtered_data = utils.filter(detrended_data, lowcut=1, highcut=20)  # 滤波
            normalized_data = utils.z_score_normalize(filtered_data)  # 归一化
            tensor_data = torch.tensor(np.ascontiguousarray(normalized_data))
            # STA/LTA 检测
            cft = classic_sta_lta(input_trace.data, int(SHORT_WINDOW / sampling_interval), int(LONG_WINDOW / sampling_interval))
            cft_triggers = trigger_onset(cft, THRESH_ON, THRESH_OFF)
            
            all_events_data = []
            for trigger in cft_triggers:
                event_start_sample = trigger[0]
                event_end_sample = trigger[1]
                event_duration = (event_end_sample - event_start_sample) * sampling_interval
                
                pre_event_time = (windows - event_duration) / 3
                post_event_time = windows - event_duration - pre_event_time
                
                start_time = input_trace.stats.starttime + event_start_sample * sampling_interval - pre_event_time
                end_time = start_time + windows
                
                if start_time < input_trace.stats.starttime:
                    start_time = input_trace.stats.starttime
                    end_time = start_time + windows
                if end_time > input_trace.stats.endtime:
                    end_time = input_trace.stats.endtime
                    start_time = end_time - windows

                # 裁剪 Z 分量
                trimmed_Z = input_trace.copy().trim(starttime=start_time, endtime=end_time, pad=True, fill_value=0)
                # 裁剪 E 分量
                trimmed_E = input_E.copy().trim(starttime=start_time, endtime=end_time, pad=True, fill_value=0)
                # 裁剪 N 分量
                trimmed_N = input_N.copy().trim(starttime=start_time, endtime=end_time, pad=True, fill_value=0)
                
                # 统一长度
                expected_points = int(windows * sampling_frequency)
                def pad_trace(trace_data):
                    if len(trace_data) < expected_points:
                        padding = np.zeros(expected_points - len(trace_data))
                        return np.concatenate((trace_data, padding))
                    return trace_data
                
                trimmed_Z.data = pad_trace(trimmed_Z.data)
                trimmed_E.data = pad_trace(trimmed_E.data)
                trimmed_N.data = pad_trace(trimmed_N.data)
                
                # 合并为三分量波形
                event_tensor = torch.tensor(
                    [trimmed_Z.data, trimmed_E.data, trimmed_N.data], dtype=torch.float32
                )
                all_events_data.append(event_tensor)
            if all_events_data == []:
                self.show_1.setText(f"Extraction failed: 0 candidate events detected. Please change data or adjust thresholds.")
                return
            # 转换为单个张量
            all_events_tensor = torch.stack(all_events_data)  # Shape: [num_events, 3, num_samples]
            # 保存结果
            # 获取当前工作目录
            current_dir = os.path.dirname(os.path.abspath(__file__))
            output_filename = os.path.join(current_dir, 'events.pt')
            torch.save(all_events_tensor, output_filename)
            
            self.show_1.setText(f"Extraction completed {len(cft_triggers)} candidate events detected. Saved to {output_filename}")
        except Exception as e:
            self.show_1.setText(f"Extraction failed:\n{str(e)}")
  
    # 设置输出路径
    def choosefile(self):
        # 选择输出路径
        file_path = QtWidgets.QFileDialog.getExistingDirectory(None, "Select Output Folder", "./")  # 起始路径
        #显示路径
        if file_path:
            self.lineEdit_8.setText(file_path)
    
    # 清空所有
    def clear(self):
        # 清空所有 QLineEdit
        line_edits = [
            self.lineEdit_1, self.lineEdit_2, self.lineEdit_3,
            self.lineEdit_4, self.lineEdit_5, self.lineEdit_6,
            self.lineEdit_7, self.lineEdit_8
        ]
        for line_edit in line_edits:
            line_edit.clear()

        self.show_1.clear()    
        # 清空所有 widget
        widgets = [self.widget_1, self.widget_2, self.widget_3]
        for widget_ in widgets:
            layout = widget_.layout()   # 获取当前显示图像的布局
            while layout.count():
                item = layout.takeAt(0)
                if item.widget():
                    item.widget().deleteLater()  # 安全销毁组件    
            
        